# As of Jan 2025, llvmlite must be compiled from https://github.com/ngoldbaum/llvmlite/tree/3.14t using LLVM 20
# numba and sparse must be installed afterward with --no-deps
name: layercake_ft
channels:
  - conda-forge
dependencies:
  - python-freethreading
  - pip
  - pip:
    - matplotlib
    - numpy
    - scipy
    - sympy
    - pebble
    - cmake #(temporary to install llvmlite)

